version: "3.3"

services:
  mongodb:
    image: mongo:3.6.20-xenial
    ports:
      - "27017:27017"
    env_file:
      - variables.env

  postgres:
    image: postgres:12.3-alpine
    ports:
      - "5432:5432"
    env_file:
      - variables.env
    volumes:
      - "postgres-storage:/var/lib/postgresql/data"

  centrifugo:
    image: centrifugo/centrifugo:v2.8
    ports:
      - "8000:8000"
      - "8100:8100"
    env_file:
      - variables.env

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elastic-storage:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  rosseti-innovation-back:
    depends_on:
      - mongodb
      - postgres
      - elastic
    build: ./
    image: sqsinformatique/rosseti-innovation-back
    env_file:
      - variables.env
    command: serve
    ports:
      - "9000:9000"
      - "9100:9100"
    restart: on-failure

volumes:
  postgres-storage:
  elastic-storage:
    driver: local
